### ISSUE TITLE
Custom 'CorrelationId' name required

### ISSUE THREAD

**Issue by shanerogers** [ekmsystems/serilog-enrichers-correlation-id#1]
Hey there. I'm interested in using this component. However, we are required to have another name for logging the correlation id. We need to use requestId not the default. Is it possible to have this library extended to allow this?

For example:

Log.Logger = new LoggerConfiguration()
    .Enrich.**WithCorrelationId("RequestId")**
    // ...other configuration...
    .CreateLogger();

**Comment by mrstebo** [comment]
Will `WithCorrelationIdHeader(headerKey)` do what you want?

**Comment by shanerogers** [comment]
Sorry yes.
