### ISSUE TITLE
Get the correlation id from code?

### ISSUE THREAD

**Issue by PaddySe** [ekmsystems/serilog-enrichers-correlation-id#12]
Is it possible to get the correlation id of the current web request?

I would like to include the correlation id in a custom error e-mail message to help in finding related log SQL table log entries.

Perhaps make CorrelationIdEnricher.CorrelationIdItemName public instead och private, so I can read the current value from HttpContext.Current.Items?

**Comment by mrstebo** [comment]
Sure! Another idea would be to inject some configuration so that you could set the name of the item in the context

**Comment by ejcoyle88** [comment]
This seems like a similar issue to #34. Maybe we can solve both issues in one go somehow?

**Comment by lkurzyniec** [comment]
@PaddySe You can use `IHttpContextAccessor` to do so. By adding `services.AddHttpContextAccessor();` in your `Startup` class, you can inject `IHttpContextAccessor`. Keep in mind that `IHttpContextAccessor` comes from `Microsoft.AspNetCore.Http`, so it's rather closer to API than to Service.

```
contextAccessor.HttpContext.Request.Headers.TryGetValue()
```

**Comment by BvdVen** [comment]
@lkurzyniec I tried this, but somehow I don't find the correlationId Header within the HttpContext.
Startup.cs:
```
Log.Logger = new LoggerConfiguration()
                .ReadFrom.Configuration(Configuration)
                .Enrich.WithCorrelationIdHeader("my-correlation-id")
            .CreateLogger();
```
TestController.cs
```
public TestController(ILogger<TestController> logger, IHttpContextAccessor contextAccessor)
 {
            StringValues stringValues = contextAccessor.HttpContext.Request.Headers["my-correlation-id"];
}
```

**Comment by lkurzyniec** [comment]
@BvdVen but you need to supply this header in the request.

![image](https://user-images.githubusercontent.com/5943484/68860381-b5796580-06e9-11ea-8cd6-5bb06d482b90.png)

**Comment by BvdVen** [comment]
@lkurzyniec but I want the first service to generate a correlationId and use that one to pass it to the next call.

**Comment by lkurzyniec** [comment]
Here you go proper snippet
```
    public class CorrelationIdMiddleware
    {
        private readonly RequestDelegate _next;

        public CorrelationIdMiddleware(RequestDelegate next)
        {

            _next = next;
        }

        public Task Invoke(HttpContext httpContext)
        {      
            var correlationId = Guid.NewGuid().ToString();

            httpContext.Request.Headers.TryGetValue("my-correlation-id", out var values);
            if (values.Any())
            {
                correlationId = values.First();
            }

            if (!httpContext.Response.Headers.ContainsKey("my-correlation-id"))
            {
                httpContext.Response.Headers.Add("my-correlation-id", correlationId);
            }

            return _next(httpContext);
        }
    }
```
And then in `Startup` class
```
builder.UseMiddleware<CorrelationIdMiddleware>();
```

---

I'm working on PR for this repository to add Middleware to rewrite `correlationId` from requesto to response. Should be ready in next week.

**Comment by BvdVen** [comment]
@lkurzyniec Thanks I'll look into this snippet if it works as I expect :) I thought the CorrelationId would be created when it wasn't provided in the header. Therefore I hoped I could get it from the ContextAccesor.

**Comment by lkurzyniec** [comment]
This snippet creates correlationId when it is not provided in the request ;-)

**Comment by BvdVen** [comment]
@lkurzyniec yes this works as I wanted 👍 . I changed it a bit so it also set the created correlationId on the request, this way I can copy the header value to outgoing request to.

Would this be an option to add to this package so people can optional use this middleware or is it not within the domain of this package?

```
public Task Invoke(HttpContext httpContext)
        {
            if (httpContext == null)
            {
                return next(httpContext);
            }

            var correlationId = Guid.NewGuid().ToString();

            httpContext.Request.Headers.TryGetValue("my-correlation-id", out var values);
            if (values.Any())
            {
                correlationId = values.First();
            }
            else
            {
                httpContext.Request.Headers.Add("my-correlation-id", correlationId);
            }

            if (!httpContext.Response.Headers.ContainsKey("my-correlation-id"))
            {
                httpContext.Response.Headers.Add("my-correlation-id", correlationId);
            }

            return next(httpContext);
        }
```

**Comment by lkurzyniec** [comment]
Already added, waiting for code review :D
https://github.com/ekmsystems/serilog-enrichers-correlation-id/pull/36

**Comment by BvdVen** [comment]
I've also found this article https://devblogs.microsoft.com/aspnet/improvements-in-net-core-3-0-for-troubleshooting-and-monitoring-distributed-apps/
that would make this package obsolete I guess? What are your thoughts on this?

**Comment by lkurzyniec** [comment]
I don't think so :D Take a look here: https://andrewlock.net/logging-using-diagnosticsource-in-asp-net-core/#when-to-use-diagnosticsource-vs-ilogger-
