### ISSUE TITLE
What is the status of this project?

### ISSUE THREAD

**Issue by OndrejValenta** [ekmsystems/serilog-enrichers-correlation-id#13]
Is it still in active development? There is a nuspec and code prepared for .NET Standard release but it's not deployed into Nuget? Can you deploy it?

**Comment by ejcoyle88** [comment]
Hi, sorry for the lack of updates on this project. We tried a while ago to sort the build errors out, but had trouble, and then I didn't have time to work on it for a while.

We're going to be using this in production going forwards, so I'm working on getting it back into a good state.

**Comment by ejcoyle88** [comment]
I'm going to close this, but if there's any more questions please feel free to reopen.
