### ISSUE TITLE
Port to .NET Standard

### ISSUE THREAD

**Issue by MovGP0** [ekmsystems/serilog-enrichers-correlation-id#2]
I get the warning message 

> Warning	NU1701	Package 'Serilog.Enrichers.CorrelationId 1.0.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.

A Port to .NET Standard should be easily possible and fix this warning.

**Comment by mrstebo** [comment]
The only pain point is the use of `HttpContext` 😅

**Comment by MovGP0** [comment]
I guess you could implement a middleware that sets the CorrelationId in the HttpContext.

**Comment by mrstebo** [comment]
I've started working on a port to .NET Core, but they have removed `HttpContext.Current`, and instead have created a `IHttpContextAccessor` that you can inject to get the HttpContext for the current request.

Somehow I'm going to have to try and plumb that in while attempting to keep the guts of the code compatible with both .NET 4.5 and .NET Core 🤔 

Hopefully [this article](https://www.strathweb.com/2016/12/accessing-httpcontext-outside-of-framework-components-in-asp-net-core/) could lead to some ideas...

**Comment by MovGP0** [comment]
It should be possible to set the `IHttpContextAccessor` when injecting the `ILogger` instance into the controller. But it requires configuration in the DI.

**Comment by mrstebo** [comment]
The whole `IHttpContextAccessor` seems like a bit 🤢 ...

I quite liked your idea of implementing a middleware. I have started something [here](https://github.com/mrstebo/serilog-enrichers-correlation-id/blob/feature/create-dot-net-core-build/src/Serilog.Enrichers.CorrelationId/Middleware/CorrelationIdMiddleware.cs), what do you think?

**Comment by MovGP0** [comment]
I doubt that it's a good idea to set the correlation ID on the global logger, because it's highly likely that there will be multiple requests at the same time.

**Comment by MovGP0** [comment]
btw: there is probably no need to create your own middleware. Maybe you can use this one: 

https://github.com/stevejgordon/CorrelationId 

You can use the `ICorrelationContextAccessor` to get the correlation ID, but that might not be better to use the `IHttpContextAccessor` :-(

**Comment by mrstebo** [comment]
Yeah, you are definitely right. I was just spitballing to see if there were any easy ways to plug it in.

I guess it is going to have to be using the IHttpContextAccessor somehow... Maybe with some kind of factory method that can resolve it for the current request

**Comment by mrstebo** [comment]
I keep seeing suggestions to use LogContext.PushProperty... maybe that could be used in the middleware 🤔

**Comment by mrstebo** [comment]
Here is what I found, https://github.com/serilog/serilog/issues/875

**Comment by carl-thomas** [comment]
Is there any movement in making this fully .NET Standard compliant?

**Comment by waxtell** [comment]
I have a local branch that builds a nuget package with both full framework and standard targets.  I would love to get your feedback in a PR...

**Comment by carl-thomas** [comment]
I would be happy to help 😄

**Comment by waxtell** [comment]
Fantastic!  Unfortunately I need to be a contributor to create a remote branch 😕

**Comment by mrstebo** [comment]
@waxtell you need to create a fork of the repository, then create your branch on your own fork. And then you can create a PR from your fork back to this repository 😁

Let me know if you run into any issues 👍

**Comment by waxtell** [comment]
Whoops!  This is my first time contributing; thank you for the edification :)

Fork and PR created.  Thank you for your time and consideration!

**Comment by PankajLala** [comment]
will commit# ejcoyle88 enable the package to be used with dotnetcore project?

**Comment by moggoly** [comment]
Are there any plans up update this project to use multi-targeting for both Full Framework and .NET Core? This would eliminate the warning message that the OP mentioned.

**Comment by waxtell** [comment]
I am by no means an appveyor expert, but I suspect we're just a tag push away from having a new, multi-platform nuget package available.

**Comment by moggoly** [comment]
👍

**Comment by mrstebo** [comment]
I'll get on started on this when I get some time tonight 👍

**Comment by drmcclelland** [comment]
This is just what we wanted (I'm using .NET Core 2.1), but I didn't see it on nuget yet...    anything I can help with?

**Comment by adamoisescu** [comment]
I am waiting for it too, seems like the only step missing is pushing the new version to appveyor

**Comment by ejcoyle88** [comment]
@mrstebo Did we ever do this? I can't remember if we got the appveyor push working.

**Comment by carl-thomas** [comment]
Hi - Any news on when this will be published?

**Comment by ejcoyle88** [comment]
Got the builds working now, and merged in the code for updating to standard. For some reason the nuget package didn't deploy though. Going to be looking into that today.

**Comment by ejcoyle88** [comment]
I've released a new beta version, [v2.0.0-beta](https://github.com/ekmsystems/serilog-enrichers-correlation-id/releases/tag/v2.0.0-beta), which has support for netstandard2.0 and netstandard2.1, as well as the previous net45.

I'm going to leave this as a beta build for a little while before moving to a full release, to check everything is good first.

**Comment by ejcoyle88** [comment]
[v2.0.0](https://github.com/ekmsystems/serilog-enrichers-correlation-id/releases/tag/v2.0.0) has now been released. 

For any issues, please raise them in a seperate issue.
