### ISSUE TITLE
.Enrich.WithCorrelationIdHeader() not working

### ISSUE THREAD

**Issue by lequangnguyenqn** [ekmsystems/serilog-enrichers-correlation-id#27]
It's not work if i use WithCorrelationIdHeader().
After debugged from your codes, I found that the error come from:
`_contextAccessor.HttpContext.Response.Headers.Add(_headerKey, correlationId);`

It's complain about:
'An item with the same key has already been added. Key: Correlation-Id'

I think you need to check if it's existing or not

**Comment by ejcoyle88** [comment]
Thanks for reporting this one. :) It should be fixed in [2.0.1](https://github.com/ekmsystems/serilog-enrichers-correlation-id/releases/tag/v2.0.1).

Any other issues please let us know.
