### ISSUE TITLE
Correlation Id does not exist for service 

### ISSUE THREAD

**Issue by brandonturpin** [ekmsystems/serilog-enrichers-correlation-id#7]
We have a MVC web service that works, and it calls WCF service that does not have the correlationId

**Comment by waxtell** [comment]
I believe HttpContext.Current is always null in WCF services.  Having said that, Microsoft has ostensibly provided a "life line" for code that depends on HttpContext.Current.  Please see:  https://stackoverflow.com/a/8976857/643427

**Comment by ejcoyle88** [comment]
Hi, I'm doing a bit of clean up. Is this still an issue?
I'm going to close for now, but if there is still a problem please comment. :)
