### ISSUE TITLE
How to configure this in appsettings.json file?

### ISSUE THREAD

**Issue by StefH** [ekmsystems/serilog-enrichers-correlation-id#84]
How to configure `WithCorrelationIdHeader("abc")` in an appsettings.json file?

**Comment by hopedrivendeveloper** [comment]
You can achieve it using 
`
 "Enrich": [
      {"Name":  "WithCorrelationIdHeader", "Args":  {"headerKey":  "custom-correlation-id-header"}}
    ]
`
